version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: educell_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: educell
      POSTGRES_PASSWORD: educell_secret
      POSTGRES_DB: educell
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: educell_adminer
    restart: unless-stopped
    ports:
      - '8080:8080'
    depends_on:
      - postgres

volumes:
  postgres_data:
