/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyCoursesRouteImport } from './routes/my-courses'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as InstructorRouteImport } from './routes/instructor'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyNumberRouteImport } from './routes/verify.$number'
import { Route as LearnCourseIdRouteImport } from './routes/learn.$courseId'
import { Route as InstructorCourseIdRouteImport } from './routes/instructor.$courseId'
import { Route as CoursesIdRouteImport } from './routes/courses.$id'
import { Route as LearnCourseIdExamExamIdRouteImport } from './routes/learn.$courseId.exam.$examId'
import { Route as LearnCourseIdExamExamIdResultRouteImport } from './routes/learn.$courseId.exam.$examId.result'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCoursesRoute = MyCoursesRouteImport.update({
  id: '/my-courses',
  path: '/my-courses',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRoute = InstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyNumberRoute = VerifyNumberRouteImport.update({
  id: '/verify/$number',
  path: '/verify/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCourseIdRoute = LearnCourseIdRouteImport.update({
  id: '/learn/$courseId',
  path: '/learn/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorCourseIdRoute = InstructorCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => InstructorRoute,
} as any)
const CoursesIdRoute = CoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CoursesRoute,
} as any)
const LearnCourseIdExamExamIdRoute = LearnCourseIdExamExamIdRouteImport.update({
  id: '/exam/$examId',
  path: '/exam/$examId',
  getParentRoute: () => LearnCourseIdRoute,
} as any)
const LearnCourseIdExamExamIdResultRoute =
  LearnCourseIdExamExamIdResultRouteImport.update({
    id: '/result',
    path: '/result',
    getParentRoute: () => LearnCourseIdExamExamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/courses': typeof CoursesRouteWithChildren
  '/instructor': typeof InstructorRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/my-courses': typeof MyCoursesRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/courses/$id': typeof CoursesIdRoute
  '/instructor/$courseId': typeof InstructorCourseIdRoute
  '/learn/$courseId': typeof LearnCourseIdRouteWithChildren
  '/verify/$number': typeof VerifyNumberRoute
  '/learn/$courseId/exam/$examId': typeof LearnCourseIdExamExamIdRouteWithChildren
  '/learn/$courseId/exam/$examId/result': typeof LearnCourseIdExamExamIdResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/courses': typeof CoursesRouteWithChildren
  '/instructor': typeof InstructorRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/my-courses': typeof MyCoursesRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/courses/$id': typeof CoursesIdRoute
  '/instructor/$courseId': typeof InstructorCourseIdRoute
  '/learn/$courseId': typeof LearnCourseIdRouteWithChildren
  '/verify/$number': typeof VerifyNumberRoute
  '/learn/$courseId/exam/$examId': typeof LearnCourseIdExamExamIdRouteWithChildren
  '/learn/$courseId/exam/$examId/result': typeof LearnCourseIdExamExamIdResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/courses': typeof CoursesRouteWithChildren
  '/instructor': typeof InstructorRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/my-courses': typeof MyCoursesRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/courses/$id': typeof CoursesIdRoute
  '/instructor/$courseId': typeof InstructorCourseIdRoute
  '/learn/$courseId': typeof LearnCourseIdRouteWithChildren
  '/verify/$number': typeof VerifyNumberRoute
  '/learn/$courseId/exam/$examId': typeof LearnCourseIdExamExamIdRouteWithChildren
  '/learn/$courseId/exam/$examId/result': typeof LearnCourseIdExamExamIdResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/courses'
    | '/instructor'
    | '/leaderboard'
    | '/login'
    | '/my-courses'
    | '/profile'
    | '/register'
    | '/courses/$id'
    | '/instructor/$courseId'
    | '/learn/$courseId'
    | '/verify/$number'
    | '/learn/$courseId/exam/$examId'
    | '/learn/$courseId/exam/$examId/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/courses'
    | '/instructor'
    | '/leaderboard'
    | '/login'
    | '/my-courses'
    | '/profile'
    | '/register'
    | '/courses/$id'
    | '/instructor/$courseId'
    | '/learn/$courseId'
    | '/verify/$number'
    | '/learn/$courseId/exam/$examId'
    | '/learn/$courseId/exam/$examId/result'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/courses'
    | '/instructor'
    | '/leaderboard'
    | '/login'
    | '/my-courses'
    | '/profile'
    | '/register'
    | '/courses/$id'
    | '/instructor/$courseId'
    | '/learn/$courseId'
    | '/verify/$number'
    | '/learn/$courseId/exam/$examId'
    | '/learn/$courseId/exam/$examId/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  InstructorRoute: typeof InstructorRouteWithChildren
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MyCoursesRoute: typeof MyCoursesRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  LearnCourseIdRoute: typeof LearnCourseIdRouteWithChildren
  VerifyNumberRoute: typeof VerifyNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-courses': {
      id: '/my-courses'
      path: '/my-courses'
      fullPath: '/my-courses'
      preLoaderRoute: typeof MyCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$number': {
      id: '/verify/$number'
      path: '/verify/$number'
      fullPath: '/verify/$number'
      preLoaderRoute: typeof VerifyNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$courseId': {
      id: '/learn/$courseId'
      path: '/learn/$courseId'
      fullPath: '/learn/$courseId'
      preLoaderRoute: typeof LearnCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/$courseId': {
      id: '/instructor/$courseId'
      path: '/$courseId'
      fullPath: '/instructor/$courseId'
      preLoaderRoute: typeof InstructorCourseIdRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/courses/$id': {
      id: '/courses/$id'
      path: '/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/learn/$courseId/exam/$examId': {
      id: '/learn/$courseId/exam/$examId'
      path: '/exam/$examId'
      fullPath: '/learn/$courseId/exam/$examId'
      preLoaderRoute: typeof LearnCourseIdExamExamIdRouteImport
      parentRoute: typeof LearnCourseIdRoute
    }
    '/learn/$courseId/exam/$examId/result': {
      id: '/learn/$courseId/exam/$examId/result'
      path: '/result'
      fullPath: '/learn/$courseId/exam/$examId/result'
      preLoaderRoute: typeof LearnCourseIdExamExamIdResultRouteImport
      parentRoute: typeof LearnCourseIdExamExamIdRoute
    }
  }
}

interface CoursesRouteChildren {
  CoursesIdRoute: typeof CoursesIdRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesIdRoute: CoursesIdRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface InstructorRouteChildren {
  InstructorCourseIdRoute: typeof InstructorCourseIdRoute
}

const InstructorRouteChildren: InstructorRouteChildren = {
  InstructorCourseIdRoute: InstructorCourseIdRoute,
}

const InstructorRouteWithChildren = InstructorRoute._addFileChildren(
  InstructorRouteChildren,
)

interface LearnCourseIdExamExamIdRouteChildren {
  LearnCourseIdExamExamIdResultRoute: typeof LearnCourseIdExamExamIdResultRoute
}

const LearnCourseIdExamExamIdRouteChildren: LearnCourseIdExamExamIdRouteChildren =
  {
    LearnCourseIdExamExamIdResultRoute: LearnCourseIdExamExamIdResultRoute,
  }

const LearnCourseIdExamExamIdRouteWithChildren =
  LearnCourseIdExamExamIdRoute._addFileChildren(
    LearnCourseIdExamExamIdRouteChildren,
  )

interface LearnCourseIdRouteChildren {
  LearnCourseIdExamExamIdRoute: typeof LearnCourseIdExamExamIdRouteWithChildren
}

const LearnCourseIdRouteChildren: LearnCourseIdRouteChildren = {
  LearnCourseIdExamExamIdRoute: LearnCourseIdExamExamIdRouteWithChildren,
}

const LearnCourseIdRouteWithChildren = LearnCourseIdRoute._addFileChildren(
  LearnCourseIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CoursesRoute: CoursesRouteWithChildren,
  InstructorRoute: InstructorRouteWithChildren,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MyCoursesRoute: MyCoursesRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  LearnCourseIdRoute: LearnCourseIdRouteWithChildren,
  VerifyNumberRoute: VerifyNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
